baseURL = "www.pingfen.io"
languageCode = "en-us"
title = "青岛平分科技官网"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""
  service_name="我们的服务"
  view_all_service="查看所有服务"

  [params.homepage_meta_tags]
    meta_description = "青岛平分科技有限公司成立于2018年12月，是基于互联网技术协助政企数字化转型的公司，并为互联网用户提供智能出行、群组协作、任务追踪等产品服务。"
    meta_og_title = "青岛平分科技有限公司"
    meta_og_type = "website"
    meta_og_url = "http://www.pingfen.io"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "青岛平分科技有限公司成立于2018年12月，是基于互联网技术协助政企数字化转型的公司，并为互联网用户提供智能出行、群组协作、任务追踪等产品服务。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
	name = "服务"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "联系我们"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"